#!/usr/bin/perl
# Writes theme-words.js from themes.txt: every word that counts as a theme
# word, per theme. The game checks each word a player spells against its
# day's list, so any word on it scores the theme bonus wherever it's played.
#
#   perl gen-theme-words.pl
#
# Adding words here (and re-running this) never changes a puzzle: the calendar
# (daily-calendar.js) is only rebuilt by gen-calendar.pl.
use strict; use warnings;

open my $in, '<:raw', 'themes.txt' or die "themes.txt: $!";
my (%words, %from, @order, $cur);
while (my $l = <$in>) {
  if ($l =~ /^== (\w+) \|/) { $cur = $1; push @order, $cur; $words{$cur} = {}; next; }
  next if !$cur || $l =~ /^\s*(#|@|$)/;
  my $since = $l =~ s/^\+(\d{4}-\d\d-\d\d)\s+// ? $1 : undef;   # words that only count from that day
  for (grep { /^[a-z]{4,}$/ } split ' ', $l) { $words{$cur}{$_} = 1; $from{$cur}{$_} = $since if $since; }
}
close $in;

open my $out, '>:raw', 'theme-words.js' or die "theme-words.js: $!";
print $out "// Theme words, per theme: spelling any of them on that theme's day scores\n";
print $out "// a bonus point. Generated by gen-theme-words.pl from themes.txt - do not hand-edit.\n";
print $out "window.THEME_WORDS = {\n";
print $out "$_: \"" . join(' ', sort keys %{ $words{$_} }) . "\",\n" for @order;
print $out "};\n";
print $out "// Words that only count from a given day (added after earlier days were already in play).\n";
print $out "window.THEME_WORDS_FROM = {\n";
for my $th (grep { $from{$_} } @order) { print $out "$th: {" . join(', ', map { "$_: \"$from{$th}{$_}\"" } sort keys %{ $from{$th} }) . "},\n"; }
print $out "};\n";
close $out;
my $n = 0; $n += keys %{ $words{$_} } for @order;
print scalar(@order), " themes, $n words -> theme-words.js\n";
